### ISSUE TITLE
親のComponentを取得するときにGetComponentInParentを使うほうが分かりやすいではありませんか

### ISSUE THREAD

**Issue by silvesthu** [unity3d-jp-tutorials/2d-shooting-game#1]
素晴らしいチュートリアル読ませて頂いてありがとうございます。

すみませんが、少し分かりづらい部分があったと思いますので、
下記wikiのページ勝手に変更させて頂きました。

（Wikiを編集してしまったら、pull requestできないことを気づいてごめんなさい）

https://github.com/unity3d-jp-tutorials/2d-shooting-game/wiki/%E7%AC%AC11%E5%9B%9E-%E3%82%A8%E3%83%8D%E3%83%9F%E3%83%BC%E3%81%AEHP%E3%80%81%E5%BC%BE%E3%81%AE%E6%94%BB%E6%92%83%E5%8A%9B%E3%80%81%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E8%BF%BD%E5%8A%A0/_compare/6c90d4fb2e1315312244f9f3e8440b922551c190...18333d3f556b0161a5d63cf248e61c1dc83a4864

**Comment by anchan828** [comment]
指摘ありがとうございます。このチュートリアルは Unity4.3 の頃に作成されており、4.5 で追加された `GetComponentInParent` は登場していません。また、コードを変更すると提供しているソースすべてを書き換えなければいけないため、すぐに対応することができません。なので変更していただいたものは元に戻させていただきました。

GetComponentInParent への対応、といいますか Unity 5 への対応はしなければいけないのでそのときに行います。
